- source/PoolAllocator.cpp
> remove un-necessary include of core_generic.h from PoolAllocator.cpp

- module.json
cmsis-core already published
mbed-drivers will get 0.10.0 within hours, just need to +1 for this and will carry out updating drivers at the same time as core-util.
> Module - update cmsis and drivers minor versions

- test/EventHandler/main.cpp
- test/FunctionPointer/main.cpp
As implementations of Event and FunctionPointer were moved to this repo, tests were still in mbed drivers.
I cloned them with the full git history, might be desirable to just reference this history in the commit message (I can squashed this into one commit where the commit message contains this log for both files with commits sha plus reference back to mbed-drivers)
@bogdanm @rgrover @bremoran
> Tests for event and function pointer move

- test/EventHandler/main.cpp
- test/FunctionPointer/main.cpp
Warning fix and EvenHandler to be compatible with greentea
Report with this fixes:
```
+---------------+---------------+----------------------------------------+--------+--------------------+-------------+
| target        | platform_name | test                                   | result | elapsed_time (sec) | copy_method |
+---------------+---------------+----------------------------------------+--------+--------------------+-------------+
| frdm-k64f-gcc | K64F          | core-util-test-sharedpointer           | OK     | 1.42               | shell       |
| frdm-k64f-gcc | K64F          | core-util-test-array                   | OK     | 1.4                | shell       |
| frdm-k64f-gcc | K64F          | core-util-test-binaryheap              | OK     | 1.44               | shell …
```
> Fix EvenHandler and FunctionPointer warning

- core-util/FunctionPointer.h
- core-util/FunctionPointerBase.h
This little change increase the size and alignment guarantees of the
storage space used in `FunctionPointerbase` to store member function
pointers.
As a side effect, it also reduce the size of the `FunctionPointerBase`
class from 28 bytes to 20.
It is important to note that it is still possible to decrease the size of `FunctionPointerBase`:
* Get rid of virtual function in `FunctionPointerBase` (this change can save 4 bytes). It does not make sense to use virtual member functions just for the `clear` member function:
- Does it have to be a polymorphic call ? 
- I tried to track use cases of `FunctionPointerBase::clear` in a polymorphic way I didn't find any result in our sources, I would be glad if someone can provide me a use case.
- Even if the clear function should be polymorphic, the …
> Reduce FunctionPointerBase size and provide alignment guarantees for the storage of member function pointers

- README.md
- core-util/FunctionPointer.h
- core-util/FunctionPointerBase.h
- core-util/FunctionPointerBind.h
- test/FunctionPointer/int_types.cpp
- test/FunctionPointer/int_types.hpp
- test/FunctionPointer/lifetime.cpp
- test/FunctionPointer/lifetime.hpp
- test/FunctionPointer/main.cpp
- test/FunctionPointer/side_effects.cpp
- test/FunctionPointer/side_effects.hpp
This version of bind does away with stdarg and uses a friend class instead.  This allows FunctionPointer to work with all types of argument, including references.
> Replace bind with a version that uses const references

- core-util/FunctionPointerBase.h
Move FunctionPointerBase’s constructor and destructor to public so that they can be called by Series.
cc @bogdanm @autopulated @niklas-arm @pan-
> Support for async::Series

- core-util/PoolAllocator.h
- source/PoolAllocator.cpp
@0xc0170 @bogdanm 
I ran GreenTea against mbed-drivers using frdm-k64f-gcc. Here are the results:
mbedgt: detecting connected mbed-enabled devices...
mbedgt: detected 1 device
detected 'K64F' -> 'K64F[0]', console at '/dev/ttyACM1', mounted at '/media/rgrover/MBED2', target id '0240022652f86e0a000000000000000000000000af2193b2'
mbedgt: yotta search for mbed-target 'k64f'
calling yotta: yotta --plain search -k mbed-target:k64f target
found target 'frdm-k64f-gcc'
found target 'frdm-k64f-armcc'
mbedgt: processing 'frdm-k64f-gcc' yotta target compatible platforms...
mbedgt: processing 'K64F' platform...
mbedgt: using platform 'K64F' for test:
target_id_mbed_htm = '0240022652f86e0a000000000000000000000000af2193b2'
mount_point = '/media/rgrover/MBED2'
target_id = …
> minor improvements

- core-util/assert.h
- core-util/core-util.h
- source/assert_mbed.c
- source/assert_posix.c
(backwards compatible, but we should deprecate the confusingly named `core-util.h` which now forwards to `assert.h` in the future)
@bogdanm @bremoran
> rename core-util.h to assert.h

- README.md
- core-util/atomic_ops.h
- source/atomic_ops.cpp
Only uint variants are optimized
Added documentation explaining the process of writing an atomic op
Fixes #58
cc @bogdanm @rgrover @0xc0170 @niklas-arm
> Add optimized specializations of atomic ops

- source/assert_mbed.c
This makes it possible to detect runtime errors using mbedgt
(which is generally reading the serial port line by line, so it
expects to have newline terminators).
> Added newline termination for runtime errors

- core-util/Array.h
- core-util/BinaryHeap.h
- core-util/ExtendablePoolAllocator.h
- core-util/PoolAllocator.h
The core-util allocators (PoolAllocator, ExtendablePoolAllocator,
Array and BinaryHeap) don't have well defined copy semantics, thus
it's better to explicitly forbid copying than to rely on the
copy constructors and assignment operators generated automatically
by the compiler.
Fixes #11.
> Forbid copying of core-util container classes

- module.json
If this module gets new major version, we will need to update ualloc, minar. I am not owner to those 2.
> Module - update mbed drivers dep

- core-util/uninitialized.h
- test/uninitialized/main.cpp
An uninitialized linker script section is never touched by the C/C++ library,
allowing state to be kept across system reboots.
The macros introduced here require additional linker script support. See
comments in core-util/uninitialized.h and see
https://github.com/ARMmbed/target-frdm-k64f-gcc/pull/18 for reference.
@bogdanm @autopulated @0xc0170 
Replaces https://github.com/ARMmbed/compiler-polyfill/pull/5
> Add support for uninitialized data sections

- test/uninitialized/main.cpp
mbedgt expects the serial connection to be up the whole time from the
start message to the result message. The previous implementation of the
test printed messages across a reset, effectively killing the serial
connection in between.
Now the messages are printed all at once when the test succeeds. No
message is printed at all if the test fails, which will trigger a test
timeout.
Fixes: 03324ad ("Add support for uninitialized data sections")
@0xc0170 @bogdanm
> Fix uninitialized test for use with mbedgt

- test/FunctionPointer/main.cpp
Fixes #49 issue.
```
+---------------+---------------+----------------------------------------+---------+--------------------+-------------+
| target        | platform_name | test                                   | result  | elapsed_time (sec) | copy_method |
+---------------+---------------+----------------------------------------+---------+--------------------+-------------+
| frdm-k64f-gcc | K64F          | core-util-test-array                   | OK      | 2.38               | shell       |
| frdm-k64f-gcc | K64F          | core-util-test-binaryheap              | OK      | 2.43               | shell       |
| frdm-k64f-gcc | K64F          | core-util-test-eventhandler            | OK      | 7.73               | shell       |
| frdm-k64f-gcc | K64F          | …
```
> Test function pointer - remove serial baud change

- module.json
- test/Array/main.cpp
- test/BinaryHeap/main.cpp
- test/EventHandler/main.cpp
- test/ExtendablePoolAllocator/main.cpp
- test/FunctionPointer/main.cpp
- test/PoolAllocator/main.cpp
- test/SharedPointer/main.cpp
- test/sbrk-mini/main.cpp
- test/uninitialized/main.cpp
Test ```core-util-test-uninitialized``` is unstable. Still work to do.
Test results from ```$mbedgt -VS --report-junit JUnit.xml```:
```
mbedgt: test suite report:
+---------------+---------------+----------------------------------------+--------+--------------------+-------------+
| target        | platform_name | test suite                             | result | elapsed_time (sec) | copy_method |
+---------------+---------------+----------------------------------------+--------+--------------------+-------------+
| frdm-k64f-gcc | K64F          | core-util-test-array                   | OK     | 11.1               | shell       |
| frdm-k64f-gcc | K64F          | core-util-test-binaryheap              | OK     | 12.34              | shell       |
| frdm-k64f-gcc | K64F          | …
```
> [devel_transport] Port tests to async model

- module.json
Fixes "error: mbed-drivers does not meet specification ~0.12.0 required by core-util" reported by yotta for apps.
mbed-drivers currently depend on this module as ^1.0.0
@bogdanm @bremoran
> Module - mbed-drivers dep update to v1

- core-util/CriticalSectionLock.h
The previous implementation of CriticalSectionLock for nrf51 was only
relying to softdevice primitives sd_nvic_critical_region_enter and
sd_nvic_critical_region_exit .
If the soft device is not enabled, these functions have no effect. This
means that CriticalSectionLock was not locking anything if the softdevice
was not enabled.
This fix allow the usage of CriticalSectionLock, even if the softdevice is
not enabled. If the softdevice is not enabled, all irq are disabled until
the destruction of the lock.
This PR should be merged with: https://github.com/ARMmbed/mbed-hal-nrf51822-mcu/pull/48
> Fix CriticalSection lock for nrf51 targets.

- core-util/PoolAllocator.h
- core-util/sbrk.h
- test/sbrk-mini/main.cpp
```
+---------------+---------------+--------------------------+--------+--------------------+-------------+
| target        | platform_name | test                     | result | elapsed_time (sec) | copy_method |
+---------------+---------------+--------------------------+--------+--------------------+-------------+
| frdm-k64f-gcc | K64F          | core-util-test-sbrk-mini | OK     | 2.39               | shell       |
+---------------+---------------+--------------------------+--------+--------------------+-------------+
```
This change-set shall be merged after #83, as that one fixes the internal tests. Then this one should not cause any failure.
I would like to eliminate those 2 TODOs in PoolAllocator. I can just remove them, any suggestions?
@bremoran @mjs-arm @bogdanm
> Fix issue#54

- source/critical.c
- source/critical_nordic.c
This implementation will use sd_nvic_critical_region_enter if the
softdevice is enabled, otherwise it will use __disable_irq().
This implementation also allow a user to start a critical section while
interrupts are already disabled.
> Provide implementation of c critical sections for nrf51 platforms.

- module.json
core-util only depends on mbed-interface.h. mbed-interface.h has not had a meaningful update since 0.11.0, so the requirements of core-util should reflect that with a wider compatible version specifier.
cc @bogdanm @mjs-arm @0xc0170 @sbutcher-arm
> Relax dependency on mbed-drivers

- source/critical.c
- source/critical_posix.c
Pretty much a copy-paste from the C++ code in CriticalSectionLock.h
NOTE:  core-util doesn't compile at this moment for POSIX platforms, but
this particular file does (using target x86-linux-native).
> C critical section implementation for POSIX platforms

- source/atomic_ops.cpp
otherwise atomic_ops.cpp won't build on POSIX.
> atomic_ops.cpp: guard inclusion of cmsis.h with TARGET_LIKE_MBED

- source/critical.c
For the moment assertions need to be commented out as this code might
run when the libc initialization has not completed yet. In those cases,
an uninitialized stderr pointer will trigger a bus fault / uVisor access
fault as it points to flash (`__sf_fake_stderr`).
For reference:
ARMmbed/mbed-drivers#176 Printing to stderr attempts a write into flash
@bogdanm @0xc0170 @adbridge
> Comment out assertions in critical.c
